CREATE TABLE IF NOT EXISTS TB_CLIENTES (
	id bigserial NOT NULL,
	limite INT8 NULL,
	saldo INT8 NULL,
	CONSTRAINT CLIENTE_PKEY PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TB_TRANSACTIONS (
	id BIGSERIAL NOT NULL,
	descricao VARCHAR(255) NULL,
	realizada_em timestamptz NULL,
	tipo BPCHAR(1) NULL,
	valor INT8 NULL,
	cliente_id INT8 NULL,
	CONSTRAINT TRANSACTION_PKEY PRIMARY KEY (id),
	CONSTRAINT FK_CLIENTE_ID FOREIGN KEY (cliente_id) REFERENCES TB_CLIENTES(id)
);