version: '3.5'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rinha
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./001_ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql
      - ./002_dml.sql:/docker-entrypoint-initdb.d/02_dml.sql
    networks:
      - rinha-q1
    deploy:
      resources:
        limits:
            cpus: "0.7"
            memory: "140MB"


  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    image: jcrjuliano/rinha-q1-api
    hostname: api01
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
    networks:
      - rinha-q1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "195MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - rinha-q1
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

#  pgAdmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_LISTEN_PORT: 5050
#      PGADMIN_LISTEN_ADDRESS: localhost
#      PGADMIN_DEFAULT_SERVER: postgres
#    depends_on:
#      - postgres
#    ports:
#      - "5050:5050"
#    networks:
#      - rinha-q1

networks:
  rinha-q1:
    driver: bridge
