version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rinha
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./001_ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql
      - ./002_dml.sql:/docker-entrypoint-initdb.d/02_dml.sql
    networks:
      - rinha-q1
#    deploy:
#      resources:
#        limits:
#            cpus: "0.4"
#            memory: "100MB"


  api01:
    build:
      context: .
      dockerfile: Dockerfile
    image: jcrjuliano/rinha-q1-api
    hostname: api01
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
    networks:
      - rinha-q1
#    deploy:
#      resources:
#        limits:
#          cpus: "0.4"
#          memory: "200MB"

  api02:
    build:
      context: .
      dockerfile: Dockerfile
    image: jcrjuliano/rinha-q1-api
    hostname: api02
    environment:
      - DB_HOST=postgres
    ports:
      - "8082:8080"
    networks:
      - rinha-q1
#    deploy:
#      resources:
#        limits:
#          cpus: "0.4"
#          memory: "200MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    networks:
      - rinha-q1
#    deploy:
#      resources:
#        limits:
#          cpus: "0.3"
#          memory: "50MB"



networks:
  rinha-q1:
    driver: bridge

